version: '3'

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./mongo:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: development
      MONGO_INITDB_ROOT_PASSWORD: development
      MONGO_INITDB_DATABASE: tindev

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: development
      ME_CONFIG_MONGODB_ADMINPASSWORD: development
